export default {
  key: "servicesStep",
  value: {
    services: [
      {
        zone: {
          dynamic_calendar_opening: { hour: "14", minute: "0" },
          dynamic_calendar: {
            begin: { type: "days", value: 0 },
            end: { type: "days", value: 10 },
          },
          breaktimes: [
            [
              {
                _id: "62538c39c67f9139224e5cad",
                day: 1,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cae",
                day: 2,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5caf",
                day: 3,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cb0",
                day: 4,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cb1",
                day: 5,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
            ],
          ],
          session_type: "people",
          is_open: true,
          is_open_internal: true,
          stand_alone_calendar: false,
          dynamic_calendar_enabled: true,
          closed_days: [
            "2022-02-21",
            "2022-04-15",
            "2022-04-18",
            "2022-05-23",
            "2022-06-24",
            "2022-07-01",
            "2022-09-05",
            "2022-10-10",
            "2022-12-23",
            "2022-12-26",
          ],
          enable_repeat_form: false,
          enable_fullday_slots: false,
          _id: "61f953e766a257ff81987a3d",
          name: "Affaires diverses de chancellerie (copies conformes / légalisations...)",
          enable_external_url: false,
          external_url: "",
          openings: [
            {
              _id: "62538c39c67f9139224e5ca8",
              day: 1,
              begin_h: 8,
              begin_m: 40,
              end_h: 12,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5ca9",
              day: 2,
              begin_h: 8,
              begin_m: 40,
              end_h: 12,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5caa",
              day: 3,
              begin_h: 8,
              begin_m: 40,
              end_h: 12,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5cab",
              day: 4,
              begin_h: 8,
              begin_m: 40,
              end_h: 12,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5cac",
              day: 5,
              begin_h: 8,
              begin_m: 40,
              end_h: 12,
              end_m: 40,
            },
          ],
          custom_openings: [],
          session_duration: 10,
          session_reservation_max: 1000,
          session_people_max: 1,
          reservation_people_max: 1,
          is_priority: false,
          reservation_delay_hours: 0,
          start_opening: "2022-03-11",
          end_opening: "2029-01-01",
          enable_colors_reservation: false,
          note: {
            ar: "",
            de: "",
            en: "",
            es: "",
            fr: "",
            it: "",
            nl: "",
            pt: "",
            ru: "",
            zh: "",
          },
          external_link_for_documents:
            "https://montreal.consulfrance.org/-Notariat-",
          custom_fields: [
            {
              required: false,
              unique: false,
              values: [],
              _id: "62538c39c67f9139224e5cb2",
              type: "textInput",
              label: "Description",
              placeholder:
                "Pouvez-vous préciser le motif de votre rendez-vous ?",
              key: "0147b51c39213669",
              translations: {
                label: {
                  fr: "Description",
                  en: "Description",
                  zh: "Description",
                  ru: "Description",
                  it: "Description",
                  es: "Description",
                  ar: "Description",
                  de: "Description",
                  pt: "Description",
                  nl: "Description",
                },
                placeholder: {
                  fr: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  en: "Why do you need an appointment?",
                  zh: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  ru: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  it: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  es: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  ar: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  de: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  pt: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  nl: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                },
              },
            },
          ],
          service_color: "#ffcdc7",
        },
        zone_id: "61f953e766a257ff81987a3d",
        external_link_for_documents:
          "https://montreal.consulfrance.org/-Notariat-",
        label:
          "Affaires diverses de chancellerie (copies conformes / légalisations...)",
        name: "Affaires diverses de chancellerie (copies conformes / légalisations...)",
        numberOfSlots: 1,
        maxSlots: 5,
      },
      {
        zone: {
          dynamic_calendar_opening: { hour: "18", minute: "0" },
          dynamic_calendar: {
            begin: { type: "days", value: 0 },
            end: { type: "days", value: 45 },
          },
          breaktimes: [
            [
              {
                _id: "62538c39c67f9139224e5cd0",
                day: 1,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cd1",
                day: 2,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cd2",
                day: 3,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cd3",
                day: 4,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cd4",
                day: 5,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
            ],
            [
              {
                _id: "62538c39c67f9139224e5cd5",
                day: 1,
                begin_h: 10,
                begin_m: 30,
                end_h: 10,
                end_m: 45,
              },
              {
                _id: "62538c39c67f9139224e5cd6",
                day: 2,
                begin_h: 10,
                begin_m: 30,
                end_h: 10,
                end_m: 45,
              },
              {
                _id: "62538c39c67f9139224e5cd7",
                day: 3,
                begin_h: 10,
                begin_m: 30,
                end_h: 10,
                end_m: 45,
              },
              {
                _id: "62538c39c67f9139224e5cd8",
                day: 4,
                begin_h: 10,
                begin_m: 30,
                end_h: 10,
                end_m: 45,
              },
              {
                _id: "62538c39c67f9139224e5cd9",
                day: 5,
                begin_h: 10,
                begin_m: 30,
                end_h: 10,
                end_m: 45,
              },
            ],
          ],
          session_type: "people",
          is_open: true,
          is_open_internal: true,
          stand_alone_calendar: false,
          dynamic_calendar_enabled: true,
          closed_days: [
            "2022-02-21",
            "2022-04-15",
            "2022-04-18",
            "2022-05-23",
            "2022-06-24",
            "2022-07-01",
            "2022-09-05",
            "2022-10-10",
            "2022-12-23",
            "2022-12-26",
          ],
          enable_repeat_form: false,
          enable_fullday_slots: false,
          _id: "623e3c5319ec2e40dcf76397",
          name: "Demande de passeport/CNI",
          enable_external_url: false,
          external_url: "",
          openings: [
            {
              _id: "62538c39c67f9139224e5ccb",
              day: 1,
              begin_h: 8,
              begin_m: 45,
              end_h: 15,
              end_m: 30,
            },
            {
              _id: "62538c39c67f9139224e5ccc",
              day: 2,
              begin_h: 8,
              begin_m: 45,
              end_h: 15,
              end_m: 30,
            },
            {
              _id: "62538c39c67f9139224e5ccd",
              day: 3,
              begin_h: 8,
              begin_m: 45,
              end_h: 15,
              end_m: 30,
            },
            {
              _id: "62538c39c67f9139224e5cce",
              day: 4,
              begin_h: 8,
              begin_m: 45,
              end_h: 15,
              end_m: 30,
            },
            {
              _id: "62538c39c67f9139224e5ccf",
              day: 5,
              begin_h: 8,
              begin_m: 45,
              end_h: 15,
              end_m: 30,
            },
          ],
          custom_openings: [],
          session_duration: 15,
          session_reservation_max: 1000,
          session_people_max: 2,
          reservation_people_max: 1,
          is_priority: false,
          reservation_delay_hours: 0,
          start_opening: "2022-03-28",
          end_opening: "2029-01-01",
          enable_colors_reservation: false,
          note: {
            ar: "",
            de: "",
            en: "",
            es: "",
            fr: "",
            it: "",
            nl: "",
            pt: "",
            ru: "",
            zh: "",
          },
          external_link_for_documents:
            "https://montreal.consulfrance.org/Demander-un-passeport-ou-une-carte-d-identite",
          custom_fields: [],
          service_color: "#ff89f3",
        },
        zone_id: "623e3c5319ec2e40dcf76397",
        external_link_for_documents:
          "https://montreal.consulfrance.org/Demander-un-passeport-ou-une-carte-d-identite",
        label: "Demande de passeport/CNI",
        name: "Demande de passeport/CNI",
        numberOfSlots: 0,
        maxSlots: 5,
      },
      {
        zone: {
          dynamic_calendar_opening: { hour: "14", minute: "0" },
          dynamic_calendar: {
            begin: { type: "days", value: 1 },
            end: { type: "days", value: 30 },
          },
          breaktimes: [
            [
              {
                _id: "62538c39c67f9139224e5cc4",
                day: 1,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cc5",
                day: 2,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cc6",
                day: 3,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cc7",
                day: 4,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5cc8",
                day: 5,
                begin_h: 13,
                begin_m: 0,
                end_h: 14,
                end_m: 0,
              },
            ],
          ],
          session_type: "people",
          is_open: true,
          is_open_internal: true,
          stand_alone_calendar: false,
          dynamic_calendar_enabled: true,
          closed_days: [
            "2022-02-21",
            "2022-04-15",
            "2022-04-18",
            "2022-05-23",
            "2022-06-24",
            "2022-07-01",
            "2022-09-05",
            "2022-10-10",
            "2022-12-23",
            "2022-12-26",
          ],
          enable_repeat_form: false,
          enable_fullday_slots: false,
          _id: "61f955a5456683ff9569d0bc",
          name: "Etat civil",
          enable_external_url: false,
          external_url: "",
          openings: [
            {
              _id: "62538c39c67f9139224e5cbf",
              day: 1,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 20,
            },
            {
              _id: "62538c39c67f9139224e5cc0",
              day: 2,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 20,
            },
            {
              _id: "62538c39c67f9139224e5cc1",
              day: 3,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 20,
            },
            {
              _id: "62538c39c67f9139224e5cc2",
              day: 4,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 20,
            },
            {
              _id: "62538c39c67f9139224e5cc3",
              day: 5,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 20,
            },
          ],
          custom_openings: [],
          session_duration: 20,
          session_reservation_max: 1000,
          session_people_max: 1,
          reservation_people_max: 1,
          is_priority: false,
          reservation_delay_hours: 0,
          start_opening: "2022-02-28",
          end_opening: "2029-01-01",
          enable_colors_reservation: false,
          note: {
            ar: "",
            de: "",
            en: "",
            es: "",
            fr: "Bonjour,\\n\\nSi vous prenez rdv pour un autre service (passeport, légalisation ... ) ou pour une démarche autre que celles indiquées en description, celui-ci ne pourra pas être honoré.\\n\\nVeillez à annuler votre rdv en cas d'impossibilité de vous présenter.\\n\\nVeuillez vous présenter 15 minutes à l'avance afin de passer le contrôle de sécurité.\\n\\nMerci de votre compréhension.\\n\\nLe service état civil.",
            it: "",
            nl: "",
            pt: "",
            ru: "",
            zh: "",
          },
          external_link_for_documents:
            "https://montreal.consulfrance.org/Enregistrer-une-naissance-un-mariage-ou-un-deces",
          custom_fields: [
            {
              required: true,
              unique: false,
              values: [],
              _id: "62538c39c67f9139224e5cc9",
              type: "textInput",
              label:
                "Prise de rdv uniquement pour une déclaration de naissance (enfant âgé de moins de 30 jours) ou pour une reconnaissance.",
              placeholder:
                "Votre rendez-vous concerne-t-il une déclaration de naissance de moins de 30 jours ou une reconnaissance ?",
              key: "26a1d468b87ff34b",
              translations: {
                label: {
                  fr: "Prise de rdv uniquement pour une déclaration de naissance (enfant âgé de moins de 30 jours) ou pour une reconnaissance.",
                  en: "Description",
                  zh: "Description",
                  ru: "Description",
                  it: "Description",
                  es: "Description",
                  ar: "Description",
                  de: "Description",
                  pt: "Description",
                  nl: "Description",
                },
                placeholder: {
                  fr: "Votre rendez-vous concerne-t-il une déclaration de naissance de moins de 30 jours ou une reconnaissance ?",
                  en: "Why do you need an appointment?",
                  zh: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  ru: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  it: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  es: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  ar: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  de: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  pt: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                  nl: "Pouvez-vous préciser le motif de votre rendez-vous ?",
                },
              },
            },
          ],
          service_color: "#dbb0f4",
        },
        zone_id: "61f955a5456683ff9569d0bc",
        external_link_for_documents:
          "https://montreal.consulfrance.org/Enregistrer-une-naissance-un-mariage-ou-un-deces",
        label: "Etat civil",
        name: "Etat civil",
        numberOfSlots: 0,
        maxSlots: 5,
      },
      {
        zone: {
          dynamic_calendar_opening: { hour: "14", minute: "0" },
          dynamic_calendar: {
            begin: { type: "days", value: 0 },
            end: { type: "days", value: 15 },
          },
          breaktimes: [
            [
              {
                _id: "62538c39c67f9139224e5ca2",
                day: 1,
                begin_h: 12,
                begin_m: 40,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5ca3",
                day: 2,
                begin_h: 12,
                begin_m: 40,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5ca4",
                day: 3,
                begin_h: 12,
                begin_m: 40,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5ca5",
                day: 4,
                begin_h: 12,
                begin_m: 40,
                end_h: 14,
                end_m: 0,
              },
              {
                _id: "62538c39c67f9139224e5ca6",
                day: 5,
                begin_h: 12,
                begin_m: 40,
                end_h: 14,
                end_m: 0,
              },
            ],
          ],
          session_type: "people",
          is_open: true,
          is_open_internal: true,
          stand_alone_calendar: false,
          dynamic_calendar_enabled: true,
          closed_days: [
            "2022-02-21",
            "2022-04-15",
            "2022-04-18",
            "2022-05-23",
            "2022-06-24",
            "2022-07-01",
            "2022-09-05",
            "2022-10-10",
            "2022-12-23",
            "2022-12-26",
          ],
          enable_repeat_form: false,
          enable_fullday_slots: false,
          _id: "61f953226dd45bff30f01db0",
          name: "RETRAIT DE CNI/PASSEPORT",
          enable_external_url: false,
          external_url: "",
          openings: [
            {
              _id: "62538c39c67f9139224e5c9d",
              day: 1,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5c9e",
              day: 2,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5c9f",
              day: 3,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5ca0",
              day: 4,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 40,
            },
            {
              _id: "62538c39c67f9139224e5ca1",
              day: 5,
              begin_h: 8,
              begin_m: 40,
              end_h: 15,
              end_m: 40,
            },
          ],
          custom_openings: [],
          session_duration: 10,
          session_reservation_max: 1000,
          session_people_max: 1,
          reservation_people_max: 1,
          is_priority: false,
          reservation_delay_hours: 0,
          start_opening: "2022-03-14",
          end_opening: "2029-01-01",
          enable_colors_reservation: false,
          note: {
            ar: "",
            de: "",
            en: "",
            es: "",
            fr: "",
            it: "",
            nl: "",
            pt: "",
            ru: "",
            zh: "",
          },
          external_link_for_documents:
            "https://montreal.consulfrance.org/Demander-un-passeport-ou-une-carte-d-identite",
          custom_fields: [],
          service_color: "#f5ebce",
        },
        zone_id: "61f953226dd45bff30f01db0",
        external_link_for_documents:
          "https://montreal.consulfrance.org/Demander-un-passeport-ou-une-carte-d-identite",
        label: "RETRAIT DE CNI/PASSEPORT",
        name: "RETRAIT DE CNI/PASSEPORT",
        numberOfSlots: 0,
        maxSlots: 5,
      },
    ],
    numberOfApplicants: 1,
  },
  stepIndex: 0,
};
